import os

env = os.environ

USER_ID = env.get('USER_ID')
CHANNEL_ACCESS_TOKEN = env.get('CHANNEL_ACCESS_TOKEN')
CHANNEL_SECRET = env.get('CHANNEL_SECRET')
EVERNOTE_SANDBOX_ACCESS_TOKEN = env.get('EVERNOTE_SANDBOX_ACCESS_TOKEN')